AVL = AVL/avl.c AVL/avl.h
UBT = UBT/ubt.c UBT/ubt.h
BT = binary_tree/binary_tree.c binary_tree/binary_tree.h

compile_avl:
	gcc $(AVL) $(BT) -o avl -lm
compile_ubt:
	gcc $(UBT) $(BT) -o ubt -lm
clear_avl:
	rm avl
	rm ubt